version: '3.1'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
         - "80:80"
         - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./certs:/etc/nginx/certs:ro
          - ./vhostd:/etc/nginx/vhost.d
          - ./html:/usr/share/nginx/html
        labels:
          - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion:v1.13
        restart: always
        environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes:
          - ./certs:/etc/nginx/certs:rw
          - ./vhostd:/etc/nginx/vhost.d
          - ./html:/usr/share/nginx/html
          - /var/run/docker.sock:/var/run/docker.sock:ro

    wordpress:
        image: wordpress
        container_name: wordpress_1
        links:
         - mariadb:mysql
        expose:
         - 80
        environment:
         - WORDPRESS_DB_PASSWORD=qwertyqwerty
         - WORDPRESS_DB_USER=userwp
         - WORDPRESS_DB_NAME=wpdb
         - "VIRTUAL_HOST=web1.utponline.xyz"
         - "LETSENCRYPT_HOST=web1.utponline.xyz"
         - "LETSENCRYPT_EMAIL=jose.moreno@comunidaddojo.org"
        volumes:
         - ./web1/html:/var/www/html

    mariadb:
        image: mariadb
        environment:
         - MYSQL_ROOT_PASSWORD=qwerty123456789
         - MYSQL_DATABASE=wpdb
         - MYSQL_USER=userwp
         - MYSQL_PASSWORD=qwertyqwerty
        volumes:
         - ./database:/var/lib/mysql

    ghost:
        image: ghost 
        expose:
         - 80
        environment:
            - VIRTUAL_HOST=ghost.utponline.xyz
            - VIRTUAL_PORT=2368
            - "LETSENCRYPT_HOST=ghost.utponline.xyz"
            - "LETSENCRYPT_EMAIL=jose.moreno@comunidaddojo.org"